spring.application.name=demo

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Wzy_20041216
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres

server.port=8080

#actix-web.http.web.url = http://47.108.27.238
#actix-web.https.web.url = https://47.108.27.238
#actix-web.http.api.url = http://47.108.27.238/api
actix-web.http.api.url = http://localhost/api
#actix-web.https.api.url = https://47.108.27.238/api

actix-web.url=${ACTIX_WEB_URL:${actix-web.http.api.url}}
auth.username=wzy
auth.password=123456

using-tcp=false

## MQTT configuration
mqtt.connection.timeout=60
mqtt.keep.alive.interval=90
mqtt.automatic.reconnect=true
mqtt.clean.session=false
