spring.application.name=demo

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=scu301
spring.datasource.password=301
spring.datasource.url=jdbc:postgresql://47.108.27.238:5432/db123

server.port=8080

#actix-web.http.web.url = http://47.108.27.238
#actix-web.https.web.url = https://47.108.27.238
actix-web.http.api.url = http://47.108.27.238/api
#actix-web.http.api.url = http://localhost/api
#actix-web.https.api.url = https://47.108.27.238/api

actix-web.url=${ACTIX_WEB_URL:${actix-web.http.api.url}}
auth.username=wzy
auth.password=123456

using-tcp=false

## MQTT configuration
mqtt.enabled=true
mqtt.connection.timeout=60
mqtt.keep.alive.interval=90
mqtt.automatic.reconnect=true
mqtt.clean.session=false
mqtt.brokerUrl=tcp://broker.emqx.io:1883
#mqtt.brokerUrl=tcp://localhost:1883
mqtt.clientId=demo
mqtt.topic=host